language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=dabl
  matrix:
    # this if failing, figure out later
    #  - DISTRIB="conda" PYTHON_VERSION="3.5"
    #    NUMPY_VERSION="1.11.*" SCIPY_VERSION="0.17.0" CYTHON_VERSION="0.23.4"
    - DISTRIB="conda" PYTHON_VERSION="3.8"
      NUMPY_VERSION="*" SCIPY_VERSION="*" CYTHON_VERSION="*" SKLEARN_VERSION="0.22.*"
    - DISTRIB="conda" PYTHON_VERSION="3.8"
      NUMPY_VERSION="*" SCIPY_VERSION="*" CYTHON_VERSION="*" SKLEARN_VERSION="0.22.*"

install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
# after_success: source ci_scripts/travis/success.sh
